apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-server-ingress
spec:
  rules:
    - host: kubernates-learning.com
      http:
        paths:
          - path: /node
            pathType: Exact
            backend:
              service:
                name: node-server-service
                port:
                  number: 7001
