apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-server-ingress
spec:
  rules:
    - host: learning-kubernates-node
      http:
        paths:
          - backend:
              service:
                name: node-server-service
                port:
                  number: 80

            pathType: Exact