apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: backend-applications
  labels:
    app_name: go-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app_name: go-server
  template:
    metadata:
      name: go-server
      labels:
        app_name: go-server
    spec:
      containers:
        - name: go-server
          image: atul161/go-server
          ports:
            - containerPort: 7000
          envFrom:
            - secretRef:
                name: go-service-secret
