apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  labels:
    app: go-server

spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      name: go-server
    spec:
      containers:
        - name: go-server-container
          image:
