apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: backend-applications
spec:
  selector:
    app_name: go-server
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 7000
