apiVersion: v1
kind: Service
metadata:
  name: node-server-service
  namespace: backend-applications
spec:
  selector:
    app_name: node-server
  ports:
    - port: 7001
      protocol: TCP
      targetPort: 7001